ALTER TABLE BOARD
MODIFY BNO INT;

ALTER TABLE BOARD
MODIFY TITLE VARCHAR2(50);

ALTER TABLE BOARD
MODIFY CONTENT VARCHAR2(100);

ALTER TABLE BOARD
MODIFY WRITER VARCHAR2(20);

ALTER TABLE BOARD
MODIFY COUNT NUMBER;
