--1
SELECT STUDENT_NAME "학생 이름",STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ;

SELECT SUBSTR(ENTRANCE_DATE,1,8)
FROM TB_STUDENT;

--2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN,1,6) DESC;

--3
SELECT STUDENT_NAME,STUDENT_NO,STUDENT_ADDRESS
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE,1,4) < '2000' 
  AND SUBSTR(STUDENT_ADDRESS,1,3) IN ('경기도','강원도')
ORDER BY STUDENT_NAME;
--4
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;

--5
SELECT STUDENT_NO,POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
  AND TERM_NO = '200402'
ORDER BY POINT DESC;

--6
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ;
--7
SELECT CLASS_NAME,DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY DEPARTMENT_NAME;

--8
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
ORDER BY PROFESSOR_NAME;

--9
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
WHERE  CATEGORY = '인문사회'
ORDER BY PROFESSOR_NAME;
--10
SELECT STUDENT_NO,STUDENT_NAME, SUBSTR(AVG(POINT),1,3)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;
